services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: rwanda_drone_db_dev
    environment:
      POSTGRES_DB: rwanda_drone_community
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - drone_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:

networks:
  drone_dev_network:
    driver: bridge 