import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const adminUser = await prisma.user.findFirst({ where: { role: 'admin' } })
  if (!adminUser) {
    throw new Error('No admin user found')
  }

  // Check if form already exists
  const existing = await prisma.universalForm.findUnique({ where: { slug: 'rwanda-uas-ecosystem-mapping' } })
  if (existing) {
    console.log('Form already exists, deleting and recreating...')
    await prisma.universalForm.delete({ where: { id: existing.id } })
  }

  const form = await prisma.universalForm.create({
    data: {
      userId: adminUser.id,
      title: 'Rwanda UAS Ecosystem Mapping — Enhanced Survey',
      slug: 'rwanda-uas-ecosystem-mapping',
      description: 'This survey collects data for the comprehensive Rwanda UAS Ecosystem Mapping Report. All responses are confidential and will be used exclusively for ecosystem analysis, policy recommendations, and strategic planning. Estimated completion time: 15-20 minutes.',
      isActive: true,
      isPublic: true,
      settings: {
        submitButtonText: 'Submit Survey',
        confirmationMessage: 'Thank you for your time and valuable insights. Your responses will directly shape the Rwanda UAS Ecosystem Mapping Report and inform strategic recommendations for strengthening the sector.',
        allowMultipleSubmissions: false,
        showProgressBar: true,
        primaryColor: '#1e3a5f',
        notifyEmails: 'info@risa.gov.rw',
      },
      sections: {
        create: [
          // ===== SECTION A: Organization Profile =====
          {
            title: 'Section A: Organization Profile',
            description: 'This section captures your organization\'s identity, capabilities, and position within the UAS value chain.',
            order: 1,
            fields: {
              create: [
                {
                  label: 'A1. Organization Name',
                  name: 'a1_organization_name',
                  type: 'SHORT_TEXT',
                  order: 1,
                  validation: { required: true },
                },
                {
                  label: 'A2. Contact Person — Name',
                  name: 'a2_contact_name',
                  type: 'SHORT_TEXT',
                  order: 2,
                  validation: { required: true },
                },
                {
                  label: 'A2. Contact Person — Title',
                  name: 'a2_contact_title',
                  type: 'SHORT_TEXT',
                  order: 3,
                  validation: { required: true },
                },
                {
                  label: 'A2. Contact Person — Email',
                  name: 'a2_contact_email',
                  type: 'EMAIL',
                  order: 4,
                  validation: { required: true },
                },
                {
                  label: 'A2. Contact Person — Phone',
                  name: 'a2_contact_phone',
                  type: 'PHONE',
                  order: 5,
                  validation: { required: true },
                },
                {
                  label: 'A3. Year of establishment',
                  name: 'a3_year_established',
                  type: 'NUMBER',
                  placeholder: 'e.g. 2018',
                  order: 6,
                  validation: { required: true },
                },
                {
                  label: 'A4. Which segment of the UAS value chain does your organization primarily operate in?',
                  name: 'a4_value_chain_segment',
                  type: 'MULTIPLE_CHOICE',
                  order: 7,
                  validation: { required: true },
                  options: [
                    'Upstream: Training and Research / R&D',
                    'Upstream: Hardware and Software Supplier',
                    'Upstream: Regulations and Policy',
                    'Midstream: UAS Operator (licensed pilot operations)',
                    'Midstream: UAS Support Services (maintenance, insurance, logistics)',
                    'Midstream: UAS Data Integrator (GIS, AI, data processing)',
                    'Midstream: Infrastructure Provider (connectivity, UTM/USSP, UASports)',
                    'Downstream: End-User / Client (agriculture, health, infrastructure, security, etc.)',
                    'Downstream: Advocacy Group / Industry Association',
                    'Cross-cutting: Investor / Funder',
                    'Other',
                  ],
                },
                {
                  label: 'A4. If "Other", please specify',
                  name: 'a4_value_chain_other',
                  type: 'SHORT_TEXT',
                  order: 8,
                  validation: { required: false },
                  conditional: { dependsOn: 'a4_value_chain_segment', operator: 'equals', value: 'Other' },
                },
                {
                  label: 'A5. Does your organization also operate in a secondary segment? If yes, which one?',
                  name: 'a5_secondary_segment',
                  type: 'SHORT_TEXT',
                  order: 9,
                  validation: { required: false },
                },
                {
                  label: 'A6. Number of employees',
                  name: 'a6_employees',
                  type: 'MULTIPLE_CHOICE',
                  order: 10,
                  validation: { required: true },
                  options: ['1-5', '6-10', '11-50', '51-100', '101-500', '500+'],
                },
                {
                  label: 'A7. Geographic scope of operations',
                  name: 'a7_geographic_scope',
                  type: 'MULTIPLE_CHOICE',
                  order: 11,
                  validation: { required: true },
                  options: [
                    'Kigali only',
                    'Multiple provinces within Rwanda',
                    'Rwanda-wide',
                    'Regional (serving clients in neighboring countries)',
                    'International',
                  ],
                },
                {
                  label: 'A8. If operating regionally or internationally, list countries served',
                  name: 'a8_countries_served',
                  type: 'SHORT_TEXT',
                  order: 12,
                  validation: { required: false },
                  conditional: { dependsOn: 'a7_geographic_scope', operator: 'contains', value: 'Regional' },
                },
                {
                  label: 'A9. Annual revenue from UAS-related activities (RWF, approximate range)',
                  name: 'a9_annual_revenue',
                  type: 'MULTIPLE_CHOICE',
                  order: 13,
                  validation: { required: true },
                  options: [
                    'Under 5 million',
                    '5-20 million',
                    '20-100 million',
                    '100-500 million',
                    'Over 500 million',
                    'Not applicable / Prefer not to disclose',
                  ],
                },
              ],
            },
          },

          // ===== SECTION A (cont): Fleet and Technology Profile =====
          {
            title: 'Fleet and Technology Profile',
            description: 'Skip this subsection if your organization does not own or operate UAS aircraft.',
            order: 2,
            fields: {
              create: [
                {
                  label: 'A10. Number of UAS aircraft currently owned/operated',
                  name: 'a10_fleet_size',
                  type: 'MULTIPLE_CHOICE',
                  order: 1,
                  validation: { required: false },
                  options: ['0 (we use subcontracted operators)', '1-2', '3-5', '6-10', '11-20', '21-50', '51-100', '101+'],
                },
                {
                  label: 'A11. Types of UAS platforms used',
                  name: 'a11_platform_types',
                  type: 'CHECKBOXES',
                  order: 2,
                  validation: { required: false },
                  options: [
                    'Rotary-wing / Multirotor (quadcopter, hexacopter, etc.)',
                    'Fixed-wing UAS',
                    'VTOL (Vertical Take-Off and Landing hybrid)',
                    'Medium UAVs (10-50 kg MTOW)',
                    'Heavy UAVs (50+ kg MTOW)',
                    'High-altitude platforms / HAPS',
                    'Other',
                  ],
                },
                {
                  label: 'A11. If "Other" platform type, please specify',
                  name: 'a11_platform_other',
                  type: 'SHORT_TEXT',
                  order: 3,
                  validation: { required: false },
                },
                {
                  label: 'A12. Primary UAS brand/model #1',
                  name: 'a12_brand_1',
                  type: 'SHORT_TEXT',
                  placeholder: 'e.g. DJI Matrice 300 RTK',
                  order: 4,
                  validation: { required: false },
                },
                {
                  label: 'A12. Primary UAS brand/model #2',
                  name: 'a12_brand_2',
                  type: 'SHORT_TEXT',
                  placeholder: 'e.g. senseFly eBee X',
                  order: 5,
                  validation: { required: false },
                },
                {
                  label: 'A12. Primary UAS brand/model #3',
                  name: 'a12_brand_3',
                  type: 'SHORT_TEXT',
                  order: 6,
                  validation: { required: false },
                },
                {
                  label: 'A12. Primary UAS brand/model #4',
                  name: 'a12_brand_4',
                  type: 'SHORT_TEXT',
                  order: 7,
                  validation: { required: false },
                },
                {
                  label: 'A12. Primary UAS brand/model #5',
                  name: 'a12_brand_5',
                  type: 'SHORT_TEXT',
                  order: 8,
                  validation: { required: false },
                },
                {
                  label: 'A13. Sensors and payloads used',
                  name: 'a13_sensors_payloads',
                  type: 'CHECKBOXES',
                  order: 9,
                  validation: { required: false },
                  options: [
                    'RGB camera (standard visual)',
                    'Multispectral sensor',
                    'Thermal / Infrared sensor',
                    'LiDAR',
                    'Hyperspectral sensor',
                    'Delivery payload mechanism',
                    'Spraying system (agricultural)',
                    'Other',
                  ],
                },
                {
                  label: 'A13. If "Other" sensor/payload, please specify',
                  name: 'a13_sensors_other',
                  type: 'SHORT_TEXT',
                  order: 10,
                  validation: { required: false },
                },
                {
                  label: 'A14. Software tool #1 (mission planning, data processing, or analytics)',
                  name: 'a14_software_1',
                  type: 'SHORT_TEXT',
                  placeholder: 'e.g. Pix4D',
                  order: 11,
                  validation: { required: false },
                },
                {
                  label: 'A14. Software tool #2',
                  name: 'a14_software_2',
                  type: 'SHORT_TEXT',
                  placeholder: 'e.g. DroneDeploy',
                  order: 12,
                  validation: { required: false },
                },
                {
                  label: 'A14. Software tool #3',
                  name: 'a14_software_3',
                  type: 'SHORT_TEXT',
                  placeholder: 'e.g. QGIS',
                  order: 13,
                  validation: { required: false },
                },
                {
                  label: 'A14. Software tool #4',
                  name: 'a14_software_4',
                  type: 'SHORT_TEXT',
                  order: 14,
                  validation: { required: false },
                },
                {
                  label: 'A14. Software tool #5',
                  name: 'a14_software_5',
                  type: 'SHORT_TEXT',
                  order: 15,
                  validation: { required: false },
                },
                {
                  label: 'A15. What is your average number of UAS missions per month?',
                  name: 'a15_missions_per_month',
                  type: 'MULTIPLE_CHOICE',
                  order: 16,
                  validation: { required: false },
                  options: ['0-5', '6-15', '16-30', '31-60', '60+', 'Not applicable'],
                },
                {
                  label: 'A16. What is your estimated annual fleet utilization rate?',
                  name: 'a16_utilization_rate',
                  type: 'MULTIPLE_CHOICE',
                  order: 17,
                  validation: { required: false },
                  options: ['Under 20%', '20-40%', '41-60%', '61-80%', 'Over 80%', "Don't know / Not tracked"],
                },
              ],
            },
          },

          // ===== SECTION A (cont): Services and Application Areas =====
          {
            title: 'Services and Application Areas',
            description: '',
            order: 3,
            fields: {
              create: [
                {
                  label: 'A17. Primary services or products provided',
                  name: 'a17_services',
                  type: 'CHECKBOXES',
                  order: 1,
                  validation: { required: true },
                  options: [
                    'Drone manufacturing / Assembly',
                    'Component supply (parts, batteries, sensors)',
                    'UAS operations (surveying, mapping, inspection)',
                    'Data analytics and processing (GIS, AI, photogrammetry)',
                    'Delivery and logistics',
                    'Agricultural services (spraying, crop monitoring)',
                    'Training and education (pilot certification, technical courses)',
                    'Maintenance, repair, and overhaul (MRO)',
                    'Software development for UAS',
                    'Consulting / Advisory',
                    'Insurance for UAS operations',
                    'UTM / Airspace management services',
                    'Other',
                  ],
                },
                {
                  label: 'A17. If "Other" service, please specify',
                  name: 'a17_services_other',
                  type: 'SHORT_TEXT',
                  order: 2,
                  validation: { required: false },
                },
                {
                  label: 'A18. Sectors served',
                  name: 'a18_sectors',
                  type: 'CHECKBOXES',
                  order: 3,
                  validation: { required: true },
                  options: [
                    'Agriculture and precision farming',
                    'Healthcare / Medical delivery',
                    'Infrastructure inspection (roads, bridges, energy)',
                    'Environmental monitoring and conservation',
                    'Mining and quarry monitoring',
                    'Security and surveillance',
                    'Delivery and logistics',
                    'Media, film, and photography',
                    'Emergency response and disaster management',
                    'Surveying, mapping, and GIS',
                    'Telecommunications and network inspection',
                    'Urban planning and smart cities',
                    'Scientific research',
                    'Other',
                  ],
                },
                {
                  label: 'A18. If "Other" sector, please specify',
                  name: 'a18_sectors_other',
                  type: 'SHORT_TEXT',
                  order: 4,
                  validation: { required: false },
                },
                {
                  label: 'A19. Describe the most significant technology or service innovation your organization has introduced in the past 24 months',
                  name: 'a19_innovation',
                  type: 'LONG_TEXT',
                  order: 5,
                  validation: { required: false },
                },
              ],
            },
          },

          // ===== SECTION B: Supply Chain, Infrastructure, and Resources =====
          {
            title: 'Section B: Supply Chain, Infrastructure, and Resources',
            description: 'Rate your agreement with the following statements (1 = Strongly Disagree, 5 = Strongly Agree) and answer the follow-up questions.',
            order: 4,
            fields: {
              create: [
                {
                  label: 'Supply Chain & Infrastructure Assessment',
                  name: 'b1_b7_matrix',
                  type: 'MATRIX',
                  order: 1,
                  validation: { required: true },
                  matrixType: 'single',
                  matrixRows: [
                    'B1. The supply chain for UAS components (airframes, flight controllers, sensors, batteries) is well established and reliable in Rwanda.',
                    'B2. Locally sourced components and materials are available to reduce import dependency.',
                    'B3. Essential resources (spare parts, maintenance tools, calibration equipment) are obtainable within Rwanda without significant delays.',
                    'B4. Physical infrastructure (designated landing zones, charging stations, storage facilities) is adequate for UAS operations.',
                    'B5. Telecommunications infrastructure (cellular network, internet connectivity) reliably supports UAS command-and-control requirements nationwide.',
                    'B6. UTM/USSP (Unmanned Traffic Management) systems are functional and accessible for coordinating UAS flights.',
                    'B7. Power supply infrastructure supports reliable UAS charging and ground operations across operating areas.',
                  ],
                  matrixColumns: ['1 Strongly Disagree', '2 Disagree', '3 Neutral', '4 Agree', '5 Strongly Agree'],
                },
                {
                  label: 'B8. Percentage of UAS hardware components that are imported (%)',
                  name: 'b8_imported_pct',
                  type: 'NUMBER',
                  placeholder: 'e.g. 90',
                  order: 2,
                  validation: { required: false, min: 0, max: 100 },
                },
                {
                  label: 'B8. Percentage of UAS hardware components that are locally sourced (%)',
                  name: 'b8_local_pct',
                  type: 'NUMBER',
                  placeholder: 'e.g. 10',
                  order: 3,
                  validation: { required: false, min: 0, max: 100 },
                },
                {
                  label: 'B9. Average lead time for receiving imported UAS components (in weeks)',
                  name: 'b9_lead_time',
                  type: 'NUMBER',
                  placeholder: 'e.g. 6',
                  order: 4,
                  validation: { required: false, min: 0 },
                },
                {
                  label: 'B10. Where do you send UAS equipment for major repairs or overhaul?',
                  name: 'b10_repair_location',
                  type: 'MULTIPLE_CHOICE',
                  order: 5,
                  validation: { required: false },
                  options: [
                    'Local service provider in Rwanda',
                    'Manufacturer (abroad)',
                    'Regional service center (East Africa)',
                    'We do all maintenance in-house',
                    'Other',
                  ],
                },
                {
                  label: 'B10. If "Other", please specify',
                  name: 'b10_repair_other',
                  type: 'SHORT_TEXT',
                  order: 6,
                  validation: { required: false },
                  conditional: { dependsOn: 'b10_repair_location', operator: 'equals', value: 'Other' },
                },
                {
                  label: 'B11. What is the single biggest supply chain or infrastructure bottleneck you face?',
                  name: 'b11_bottleneck',
                  type: 'LONG_TEXT',
                  order: 7,
                  validation: { required: false },
                },
              ],
            },
          },

          // ===== SECTION C: Talent and Workforce =====
          {
            title: 'Section C: Talent and Workforce',
            description: 'Rate your agreement with the following statements and answer the follow-up questions.',
            order: 5,
            fields: {
              create: [
                {
                  label: 'Talent & Workforce Assessment',
                  name: 'c1_c5_matrix',
                  type: 'MATRIX',
                  order: 1,
                  validation: { required: true },
                  matrixType: 'single',
                  matrixRows: [
                    'C1. There is a sufficient pool of qualified UAS pilots available for hire in Rwanda.',
                    'C2. There is a sufficient pool of UAS data analysts (GIS, photogrammetry, remote sensing) available in Rwanda.',
                    'C3. There is a sufficient pool of UAS hardware engineers / maintenance technicians in Rwanda.',
                    'C4. Academic and training institutions produce graduates whose skills match UAS industry needs.',
                    'C5. On-the-job training and mentorship opportunities are accessible within the ecosystem.',
                  ],
                  matrixColumns: ['1 Strongly Disagree', '2 Disagree', '3 Neutral', '4 Agree', '5 Strongly Agree'],
                },
                {
                  label: 'C6. Hardest skill profile to recruit — Rank 1 (hardest)',
                  name: 'c6_rank1',
                  type: 'DROPDOWN',
                  order: 2,
                  validation: { required: true },
                  options: [
                    'Licensed UAS pilots',
                    'GIS / Remote sensing / Data analysts',
                    'UAS hardware engineers / Avionics',
                    'Software developers (flight control, AI/ML, analytics)',
                    'Maintenance and repair technicians',
                    'Regulatory compliance specialists',
                    'Business development / Sales for UAS services',
                    'Other',
                  ],
                },
                {
                  label: 'C6. Hardest skill profile to recruit — Rank 2',
                  name: 'c6_rank2',
                  type: 'DROPDOWN',
                  order: 3,
                  validation: { required: true },
                  options: [
                    'Licensed UAS pilots',
                    'GIS / Remote sensing / Data analysts',
                    'UAS hardware engineers / Avionics',
                    'Software developers (flight control, AI/ML, analytics)',
                    'Maintenance and repair technicians',
                    'Regulatory compliance specialists',
                    'Business development / Sales for UAS services',
                    'Other',
                  ],
                },
                {
                  label: 'C6. Hardest skill profile to recruit — Rank 3',
                  name: 'c6_rank3',
                  type: 'DROPDOWN',
                  order: 4,
                  validation: { required: true },
                  options: [
                    'Licensed UAS pilots',
                    'GIS / Remote sensing / Data analysts',
                    'UAS hardware engineers / Avionics',
                    'Software developers (flight control, AI/ML, analytics)',
                    'Maintenance and repair technicians',
                    'Regulatory compliance specialists',
                    'Business development / Sales for UAS services',
                    'Other',
                  ],
                },
                {
                  label: 'C7. What training topics would most benefit your team? (Select up to 3)',
                  name: 'c7_training_topics',
                  type: 'CHECKBOXES',
                  order: 5,
                  validation: { required: true },
                  options: [
                    'Advanced drone piloting (BVLOS, night operations)',
                    'Drone data processing and analytics (photogrammetry, NDVI, LiDAR)',
                    'UAS software development (flight planning, autonomy, AI)',
                    'UAS maintenance, repair, and overhaul',
                    'Regulatory compliance and safety management',
                    'Drone manufacturing and assembly',
                    'Business model development for UAS services',
                    'Project management for UAS operations',
                    'Other',
                  ],
                },
                {
                  label: 'C7. If "Other" training topic, please specify',
                  name: 'c7_training_other',
                  type: 'SHORT_TEXT',
                  order: 6,
                  validation: { required: false },
                },
                {
                  label: 'C8. What percentage of your UAS workforce is female?',
                  name: 'c8_female_pct',
                  type: 'MULTIPLE_CHOICE',
                  order: 7,
                  validation: { required: true },
                  options: ['0%', '1-10%', '11-25%', '26-50%', 'Over 50%'],
                },
              ],
            },
          },

          // ===== SECTION D: Regulatory Environment and Certification =====
          {
            title: 'Section D: Regulatory Environment and Certification',
            description: 'Rate your agreement with the following statements and answer the follow-up questions.',
            order: 6,
            fields: {
              create: [
                {
                  label: 'Regulatory Environment Assessment',
                  name: 'd1_d7_matrix',
                  type: 'MATRIX',
                  order: 1,
                  validation: { required: true },
                  matrixType: 'single',
                  matrixRows: [
                    'D1. The process to register a UAS and obtain operator licenses from RCAA is clear and well-documented.',
                    'D2. The time required to obtain regulatory approvals is reasonable for our operational needs.',
                    'D3. The cost of licensing, registration, and compliance is proportionate and affordable.',
                    'D4. Regulations are sufficiently flexible to accommodate new UAS applications and technologies.',
                    'D5. There is clear guidance on BVLOS (Beyond Visual Line of Sight) operations.',
                    'D6. The regulatory framework supports cross-border UAS operations within East Africa.',
                    'D7. Communication and feedback channels between operators and RCAA are effective.',
                  ],
                  matrixColumns: ['1 Strongly Disagree', '2 Disagree', '3 Neutral', '4 Agree', '5 Strongly Agree'],
                },
                {
                  label: 'D8. How long (in weeks) did it take to obtain your most recent RCAA license/approval?',
                  name: 'd8_license_time',
                  type: 'NUMBER',
                  placeholder: 'e.g. 8',
                  order: 2,
                  validation: { required: false, min: 0 },
                },
                {
                  label: 'D9. Total annual cost of regulatory compliance in RWF (registration, licensing, insurance, training certification)',
                  name: 'd9_compliance_cost',
                  type: 'NUMBER',
                  placeholder: 'e.g. 2000000',
                  order: 3,
                  validation: { required: false, min: 0 },
                },
                {
                  label: 'D10. What is the single most important regulatory improvement that would benefit the UAS sector?',
                  name: 'd10_regulatory_improvement',
                  type: 'LONG_TEXT',
                  order: 4,
                  validation: { required: false },
                },
              ],
            },
          },

          // ===== SECTION E: Technology and Knowledge Transfer =====
          {
            title: 'Section E: Technology and Knowledge Transfer',
            description: 'Rate your agreement with the following statements and answer the follow-up questions.',
            order: 7,
            fields: {
              create: [
                {
                  label: 'Technology & Knowledge Transfer Assessment',
                  name: 'e1_e5_matrix',
                  type: 'MATRIX',
                  order: 1,
                  validation: { required: true },
                  matrixType: 'single',
                  matrixRows: [
                    'E1. Collaboration between UAS companies and academic/research institutions is active and productive.',
                    'E2. International technology partnerships effectively support local UAS capability development.',
                    'E3. There are adequate platforms (conferences, workshops, hubs) for knowledge exchange within the ecosystem.',
                    'E4. Local R&D activities are generating commercially viable UAS innovations.',
                    'E5. Intellectual property protections are adequate to incentivize local UAS innovation.',
                  ],
                  matrixColumns: ['1 Strongly Disagree', '2 Disagree', '3 Neutral', '4 Agree', '5 Strongly Agree'],
                },
                {
                  label: 'E6. R&D / knowledge sharing collaborator #1',
                  name: 'e6_collaborator_1',
                  type: 'SHORT_TEXT',
                  order: 2,
                  validation: { required: false },
                },
                {
                  label: 'E6. R&D / knowledge sharing collaborator #2',
                  name: 'e6_collaborator_2',
                  type: 'SHORT_TEXT',
                  order: 3,
                  validation: { required: false },
                },
                {
                  label: 'E6. R&D / knowledge sharing collaborator #3',
                  name: 'e6_collaborator_3',
                  type: 'SHORT_TEXT',
                  order: 4,
                  validation: { required: false },
                },
                {
                  label: 'E6. R&D / knowledge sharing collaborator #4',
                  name: 'e6_collaborator_4',
                  type: 'SHORT_TEXT',
                  order: 5,
                  validation: { required: false },
                },
                {
                  label: 'E6. R&D / knowledge sharing collaborator #5',
                  name: 'e6_collaborator_5',
                  type: 'SHORT_TEXT',
                  order: 6,
                  validation: { required: false },
                },
                {
                  label: 'E7. What technology or capability gap, if addressed, would most transform your operations?',
                  name: 'e7_capability_gap',
                  type: 'LONG_TEXT',
                  order: 7,
                  validation: { required: false },
                },
              ],
            },
          },

          // ===== SECTION F: Business Viability and Access to Finance =====
          {
            title: 'Section F: Business Viability and Access to Finance',
            description: 'Rate your agreement with the following statements and answer the follow-up questions.',
            order: 8,
            fields: {
              create: [
                {
                  label: 'Business Viability & Finance Assessment',
                  name: 'f1_f6_matrix',
                  type: 'MATRIX',
                  order: 1,
                  validation: { required: true },
                  matrixType: 'single',
                  matrixRows: [
                    'F1. Our UAS-related business is financially sustainable (revenues cover costs).',
                    'F2. Demand for UAS services is sufficient to maintain consistent operations year-round.',
                    'F3. Access to startup or growth capital for UAS ventures is adequate in Rwanda.',
                    'F4. Financial institutions (banks, MFIs) understand the UAS sector and offer appropriate products.',
                    'F5. Grant funding and donor support for UAS projects is accessible.',
                    'F6. UAS insurance products are available and reasonably priced.',
                  ],
                  matrixColumns: ['1 Strongly Disagree', '2 Disagree', '3 Neutral', '4 Agree', '5 Strongly Agree'],
                },
                {
                  label: 'F7. What is your primary revenue model?',
                  name: 'f7_revenue_model',
                  type: 'MULTIPLE_CHOICE',
                  order: 2,
                  validation: { required: true },
                  options: [
                    'Per-mission / Per-flight fees',
                    'Subscription / Retainer contracts',
                    'Product sales (hardware, software)',
                    'Training and certification fees',
                    'Data / Analytics as a service',
                    'Government contracts / Tenders',
                    'Grant-funded projects',
                    'Other',
                  ],
                },
                {
                  label: 'F7. If "Other" revenue model, please specify',
                  name: 'f7_revenue_other',
                  type: 'SHORT_TEXT',
                  order: 3,
                  validation: { required: false },
                  conditional: { dependsOn: 'f7_revenue_model', operator: 'equals', value: 'Other' },
                },
                {
                  label: 'F8. What type of financing have you accessed for UAS activities?',
                  name: 'f8_financing',
                  type: 'CHECKBOXES',
                  order: 4,
                  validation: { required: true },
                  options: [
                    'Personal savings / Bootstrapping',
                    'Bank loan',
                    'Microfinance',
                    'Angel investment',
                    'Venture capital',
                    'Government grant (NCST, RDB, Innovation Fund, etc.)',
                    'International donor / Development partner grant',
                    'Competition / Challenge prize',
                    'None — unable to access financing',
                    'Not applicable',
                  ],
                },
                {
                  label: 'F9. What amount of additional investment (in USD) would your organization need over the next 2 years to reach its growth targets?',
                  name: 'f9_investment_needed',
                  type: 'MULTIPLE_CHOICE',
                  order: 5,
                  validation: { required: true },
                  options: [
                    'Under $10,000',
                    '$10,000-$50,000',
                    '$50,000-$200,000',
                    '$200,000-$1,000,000',
                    'Over $1,000,000',
                  ],
                },
                {
                  label: 'F10. What is the biggest financial barrier to growth?',
                  name: 'f10_financial_barrier',
                  type: 'LONG_TEXT',
                  order: 6,
                  validation: { required: false },
                },
              ],
            },
          },

          // ===== SECTION G: End-User Adoption and Market Dynamics =====
          {
            title: 'Section G: End-User Adoption and Market Dynamics',
            description: 'Answer from your perspective, whether as a provider or a user of UAS services.',
            order: 9,
            fields: {
              create: [
                {
                  label: 'End-User Adoption & Market Assessment',
                  name: 'g1_g5_matrix',
                  type: 'MATRIX',
                  order: 1,
                  validation: { required: true },
                  matrixType: 'single',
                  matrixRows: [
                    'G1. End-users in Rwanda are aware of the potential applications of UAS technology in their sector.',
                    'G2. End-users trust the data and outputs produced by UAS operations.',
                    'G3. End-users are willing to pay market rates for UAS services.',
                    'G4. Government agencies actively procure UAS services for public sector applications.',
                    'G5. UAS services are competitively priced compared to traditional alternatives (manned surveys, ground logistics, etc.).',
                  ],
                  matrixColumns: ['1 Strongly Disagree', '2 Disagree', '3 Neutral', '4 Agree', '5 Strongly Agree'],
                },
                {
                  label: 'G6. Who are your primary clients/customers? (Select up to 3)',
                  name: 'g6_primary_clients',
                  type: 'CHECKBOXES',
                  order: 2,
                  validation: { required: true },
                  options: [
                    'Government ministries and agencies',
                    'District local governments',
                    'International NGOs and development organizations',
                    'Agricultural cooperatives and farmer organizations',
                    'Mining companies',
                    'Construction and real estate companies',
                    'Telecommunications companies',
                    'Healthcare institutions',
                    'Media and production companies',
                    'Research institutions and universities',
                    'Private sector (other)',
                    'Individual consumers',
                  ],
                },
                {
                  label: 'G7. Average price your clients pay per UAS mission or service engagement (in RWF)',
                  name: 'g7_avg_price',
                  type: 'NUMBER',
                  placeholder: 'e.g. 500000',
                  order: 3,
                  validation: { required: false, min: 0 },
                },
                {
                  label: 'G8. What is the main reason potential clients choose NOT to use UAS services?',
                  name: 'g8_non_adoption_reason',
                  type: 'MULTIPLE_CHOICE',
                  order: 4,
                  validation: { required: true },
                  options: [
                    'Cost perceived as too high',
                    'Lack of awareness of UAS capabilities',
                    'Regulatory uncertainty or restrictions',
                    'Lack of trust in data quality',
                    'Preference for traditional methods',
                    'Difficulty integrating UAS data into existing workflows',
                    'Other',
                  ],
                },
                {
                  label: 'G8. If "Other" reason, please specify',
                  name: 'g8_non_adoption_other',
                  type: 'SHORT_TEXT',
                  order: 5,
                  validation: { required: false },
                  conditional: { dependsOn: 'g8_non_adoption_reason', operator: 'equals', value: 'Other' },
                },
              ],
            },
          },

          // ===== SECTION H: Ecosystem Connectivity and Collaboration =====
          {
            title: 'Section H: Ecosystem Connectivity and Collaboration',
            description: 'This section maps how organizations within the UAS ecosystem interact, collaborate, and exchange value. It is critical for understanding network density and identifying disconnects.',
            order: 10,
            fields: {
              create: [
                {
                  label: 'H1. Partner organization #1 (name)',
                  name: 'h1_partner_1_name',
                  type: 'SHORT_TEXT',
                  placeholder: 'Organization name',
                  order: 1,
                  validation: { required: false },
                },
                {
                  label: 'H1. Partner #1 — Relationship type',
                  name: 'h1_partner_1_type',
                  type: 'DROPDOWN',
                  order: 2,
                  validation: { required: false },
                  options: ['Partnership', 'Subcontracting', 'Referrals', 'Data sharing', 'Joint R&D', 'Other'],
                },
                {
                  label: 'H1. Partner organization #2 (name)',
                  name: 'h1_partner_2_name',
                  type: 'SHORT_TEXT',
                  order: 3,
                  validation: { required: false },
                },
                {
                  label: 'H1. Partner #2 — Relationship type',
                  name: 'h1_partner_2_type',
                  type: 'DROPDOWN',
                  order: 4,
                  validation: { required: false },
                  options: ['Partnership', 'Subcontracting', 'Referrals', 'Data sharing', 'Joint R&D', 'Other'],
                },
                {
                  label: 'H1. Partner organization #3 (name)',
                  name: 'h1_partner_3_name',
                  type: 'SHORT_TEXT',
                  order: 5,
                  validation: { required: false },
                },
                {
                  label: 'H1. Partner #3 — Relationship type',
                  name: 'h1_partner_3_type',
                  type: 'DROPDOWN',
                  order: 6,
                  validation: { required: false },
                  options: ['Partnership', 'Subcontracting', 'Referrals', 'Data sharing', 'Joint R&D', 'Other'],
                },
                {
                  label: 'H1. Partner organization #4 (name)',
                  name: 'h1_partner_4_name',
                  type: 'SHORT_TEXT',
                  order: 7,
                  validation: { required: false },
                },
                {
                  label: 'H1. Partner #4 — Relationship type',
                  name: 'h1_partner_4_type',
                  type: 'DROPDOWN',
                  order: 8,
                  validation: { required: false },
                  options: ['Partnership', 'Subcontracting', 'Referrals', 'Data sharing', 'Joint R&D', 'Other'],
                },
                {
                  label: 'H1. Partner organization #5 (name)',
                  name: 'h1_partner_5_name',
                  type: 'SHORT_TEXT',
                  order: 9,
                  validation: { required: false },
                },
                {
                  label: 'H1. Partner #5 — Relationship type',
                  name: 'h1_partner_5_type',
                  type: 'DROPDOWN',
                  order: 10,
                  validation: { required: false },
                  options: ['Partnership', 'Subcontracting', 'Referrals', 'Data sharing', 'Joint R&D', 'Other'],
                },
                {
                  label: 'H2. Desired collaboration #1 — Organization name',
                  name: 'h2_desired_1_name',
                  type: 'SHORT_TEXT',
                  order: 11,
                  validation: { required: false },
                },
                {
                  label: 'H2. Desired collaboration #1 — Why not yet?',
                  name: 'h2_desired_1_reason',
                  type: 'SHORT_TEXT',
                  order: 12,
                  validation: { required: false },
                },
                {
                  label: 'H2. Desired collaboration #2 — Organization name',
                  name: 'h2_desired_2_name',
                  type: 'SHORT_TEXT',
                  order: 13,
                  validation: { required: false },
                },
                {
                  label: 'H2. Desired collaboration #2 — Why not yet?',
                  name: 'h2_desired_2_reason',
                  type: 'SHORT_TEXT',
                  order: 14,
                  validation: { required: false },
                },
                {
                  label: 'H2. Desired collaboration #3 — Organization name',
                  name: 'h2_desired_3_name',
                  type: 'SHORT_TEXT',
                  order: 15,
                  validation: { required: false },
                },
                {
                  label: 'H2. Desired collaboration #3 — Why not yet?',
                  name: 'h2_desired_3_reason',
                  type: 'SHORT_TEXT',
                  order: 16,
                  validation: { required: false },
                },
                {
                  label: 'H3. How often do you interact with other UAS ecosystem players (outside client relationships)?',
                  name: 'h3_interaction_frequency',
                  type: 'MULTIPLE_CHOICE',
                  order: 17,
                  validation: { required: true },
                  options: [
                    'Weekly or more',
                    'Monthly',
                    'Quarterly',
                    'Annually (at events or workshops only)',
                    'Rarely or never',
                  ],
                },
                {
                  label: 'H4. Are you a member of any UAS or aviation industry association or network?',
                  name: 'h4_association_member',
                  type: 'MULTIPLE_CHOICE',
                  order: 18,
                  validation: { required: true },
                  options: [
                    'Yes',
                    'No, but interested',
                    'No, not interested',
                  ],
                },
                {
                  label: 'H4. If "Yes", please specify which association(s)',
                  name: 'h4_association_name',
                  type: 'SHORT_TEXT',
                  order: 19,
                  validation: { required: false },
                  conditional: { dependsOn: 'h4_association_member', operator: 'equals', value: 'Yes' },
                },
                {
                  label: 'H5. What type of ecosystem platform would be most valuable to you?',
                  name: 'h5_platform_preference',
                  type: 'MULTIPLE_CHOICE',
                  order: 20,
                  validation: { required: true },
                  options: [
                    'Online directory of UAS service providers',
                    'Quarterly ecosystem meetups / Networking events',
                    'Shared procurement platform (matching supply and demand)',
                    'Joint training and capacity building programs',
                    'Shared testing and calibration facilities',
                    'Other',
                  ],
                },
                {
                  label: 'H5. If "Other" platform, please specify',
                  name: 'h5_platform_other',
                  type: 'SHORT_TEXT',
                  order: 21,
                  validation: { required: false },
                  conditional: { dependsOn: 'h5_platform_preference', operator: 'equals', value: 'Other' },
                },
              ],
            },
          },

          // ===== SECTION I: Strategic Priorities and Outlook =====
          {
            title: 'Section I: Strategic Priorities and Outlook',
            description: '',
            order: 11,
            fields: {
              create: [
                {
                  label: 'I1. Top barrier to UAS ecosystem growth — Rank 1 (most critical)',
                  name: 'i1_barrier_rank1',
                  type: 'DROPDOWN',
                  order: 1,
                  validation: { required: true },
                  options: [
                    'Regulatory complexity or delays',
                    'Lack of skilled workforce',
                    'Insufficient access to capital / finance',
                    'Limited end-user awareness and demand',
                    'Infrastructure gaps (connectivity, airspace, facilities)',
                    'Import restrictions or supply chain challenges',
                    'Weak collaboration between ecosystem players',
                    'Lack of local manufacturing capability',
                    'Data privacy and security concerns',
                    'Other',
                  ],
                },
                {
                  label: 'I1. Top barrier to UAS ecosystem growth — Rank 2',
                  name: 'i1_barrier_rank2',
                  type: 'DROPDOWN',
                  order: 2,
                  validation: { required: true },
                  options: [
                    'Regulatory complexity or delays',
                    'Lack of skilled workforce',
                    'Insufficient access to capital / finance',
                    'Limited end-user awareness and demand',
                    'Infrastructure gaps (connectivity, airspace, facilities)',
                    'Import restrictions or supply chain challenges',
                    'Weak collaboration between ecosystem players',
                    'Lack of local manufacturing capability',
                    'Data privacy and security concerns',
                    'Other',
                  ],
                },
                {
                  label: 'I1. Top barrier to UAS ecosystem growth — Rank 3',
                  name: 'i1_barrier_rank3',
                  type: 'DROPDOWN',
                  order: 3,
                  validation: { required: true },
                  options: [
                    'Regulatory complexity or delays',
                    'Lack of skilled workforce',
                    'Insufficient access to capital / finance',
                    'Limited end-user awareness and demand',
                    'Infrastructure gaps (connectivity, airspace, facilities)',
                    'Import restrictions or supply chain challenges',
                    'Weak collaboration between ecosystem players',
                    'Lack of local manufacturing capability',
                    'Data privacy and security concerns',
                    'Other',
                  ],
                },
                {
                  label: 'I2. Which UAS application area has the highest untapped potential in Rwanda?',
                  name: 'i2_untapped_potential',
                  type: 'MULTIPLE_CHOICE',
                  order: 4,
                  validation: { required: true },
                  options: [
                    'Precision agriculture (crop monitoring, spraying, yield estimation)',
                    'Medical and pharmaceutical delivery',
                    'Infrastructure inspection and monitoring',
                    'Environmental conservation and forestry',
                    'Disaster risk management and emergency response',
                    'Mining and geological survey',
                    'Urban planning and cadastral mapping',
                    'Security and border monitoring',
                    'Cargo delivery and logistics',
                    'Other',
                  ],
                },
                {
                  label: 'I2. If "Other" application area, please specify',
                  name: 'i2_untapped_other',
                  type: 'SHORT_TEXT',
                  order: 5,
                  validation: { required: false },
                  conditional: { dependsOn: 'i2_untapped_potential', operator: 'equals', value: 'Other' },
                },
                {
                  label: 'I3. What one action by the Government of Rwanda would most accelerate the UAS sector?',
                  name: 'i3_government_action',
                  type: 'LONG_TEXT',
                  order: 6,
                  validation: { required: true },
                },
                {
                  label: 'I4. Where do you see the Rwanda UAS ecosystem in 5 years?',
                  name: 'i4_five_year_outlook',
                  type: 'LONG_TEXT',
                  order: 7,
                  validation: { required: false },
                },
              ],
            },
          },
        ],
      },
    },
    include: {
      sections: {
        include: {
          fields: { orderBy: { order: 'asc' } },
        },
        orderBy: { order: 'asc' },
      },
    },
  })

  const totalFields = form.sections.reduce((acc, s) => acc + s.fields.length, 0)
  console.log(`\n✅ Form created successfully!`)
  console.log(`   Title: ${form.title}`)
  console.log(`   Slug: ${form.slug}`)
  console.log(`   ID: ${form.id}`)
  console.log(`   Sections: ${form.sections.length}`)
  console.log(`   Total fields: ${totalFields}`)
  console.log(`\n   Public URL: /forms/public/${form.id}`)
  console.log(`   Edit URL: /forms/${form.id}/edit`)
}

main()
  .catch((e) => {
    console.error('❌ Error:', e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
